// Writes World 3's levels into js/levels.js (between the WORLD 3 markers)
// from the chapter files tools/w3/ch1.js … ch5.js, which stay the source:
// each chapter keeps its levels next to their proofs and naive "fails".
//   node tools/w3/build.js          (npm run build:w3)
//   node tools/w3/build.js --check  exit 1 if js/levels.js is out of date
'use strict';
const fs = require('fs');
const path = require('path');

const CHAPTERS = [
  { file: 'ch1', name: 'Keep Out' },
  { file: 'ch2', name: 'Weaving' },
  { file: 'ch3', name: 'Flip Burns' },
  { file: 'ch4', name: 'Zone Drops' },
  { file: 'ch5', name: 'Grand Missions' },
];
const BEGIN = '  // ---- BEGIN WORLD 3 (generated by tools/w3/build.js from tools/w3/ch*.js; edit those) ----';
const END = '  // ---- END WORLD 3 ----';

function generate() {
  const out = [BEGIN, '  const WORLD3 = ['];
  for (const ch of CHAPTERS) {
    out.push(`    // Chapter: ${ch.name}`);
    for (const L of require('./' + ch.file).levels) {
      const json = JSON.stringify(L, null, 2).split('\n').map(s => '    ' + s).join('\n');
      out.push(json + ',');
    }
  }
  out.push('  ];', '  for (const L of WORLD3) L.world = 3;', '  LEVELS.push(...WORLD3);', END);
  return out.join('\n');
}

const file = path.join(__dirname, '..', '..', 'js', 'levels.js');
const src = fs.readFileSync(file, 'utf8');
const a = src.indexOf(BEGIN), b = src.indexOf(END);
if (a < 0 || b < 0) { console.error('WORLD 3 markers not found in js/levels.js'); process.exit(2); }
const next = src.slice(0, a) + generate() + src.slice(b + END.length);
if (process.argv.includes('--check')) {
  if (next !== src) { console.error('js/levels.js is out of date: run npm run build:w3'); process.exit(1); }
  console.log('js/levels.js World 3 is up to date');
} else {
  fs.writeFileSync(file, next);
  console.log('wrote World 3 into js/levels.js');
}
